import { MantineProvider } from '@mantine/core';
import { Notifications } from '@mantine/notifications';
import Head from 'next/head'
import { Provider } from 'react-redux';
import { store } from '@/store';


export default function App({ Component, pageProps }) {
  return (
    <>
      <Head>
        <title>Old Rap Shop</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />

      </Head>

      <MantineProvider
        theme={{
          globalStyles: () => ({
            '*, *::before, *::after': {
              margin: "0",
              padding: "0",
              boxSizing: 'border-box',
              outline: "none"
            },
            body: {
              overflow: "hidden"
            },
            li: {
              listStyle: "none",
            },
            button: {
              border: "none",
              background: "none",
              cursor: "pointer",
              outline: "none",
            },
            input: {
              outline: "none",
              border: "0",
            },
            a: {
              textDecoration: "none"
            }
          }),
          primaryColor: 'yellow'
        }}
        withGlobalStyles
        withNormalizeCSS
      >
        <Notifications position='top-center' limit={3} />
        <Provider store={store}>
          <Component {...pageProps} />
        </Provider>
      </MantineProvider>
    </>

  )
}
